server:
  port: 8130

spring:
  webflux:
    base-path: /just-wait

management:
  endpoint:
    health:
      show-details: 'always'
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
